#!/bin/sh
case "$1" in
	*.tar*) tar tf "$1";;
	#*.zip) unzip -l "$1";;
	#*.rar) unrar l "$1";;
	#*.7z) 7z l "$1";;
	#*.pdf) pdftotext "$1" -;;
	*.png|*.jpg) jp2a $1;;
	*) head -n $3 "$1" | nl -s " │  " -b a;;
	#*) echo $1 $2 $3 $4 $5
esac

