#!/bin/sh

bspc monitor -d 1 2 3 4 5

# set some defaults variables
BSP_GAP=30
POLYBAR_HEIGHT=36
BSP_WINDOW_GAP=20


# Define a file path to store the variable
bsp_gap_file="/tmp/BSP_GAP"
echo $BSP_GAP > $bsp_gap_file

polybar_height_file="/tmp/POLYBAR_HEIGHT"
echo $POLYBAR_HEIGHT > $polybar_height_file

bsp_window_gap_file="/tmp/BSP_WINDOW_GAP"
echo $BSP_WINDOW_GAP > $bsp_window_gap_file


#set gaps
#~/.config/sxhkd/scripts/bspwm-gap toggle



# get Xresourses colors
BACKGROUND=$(xrdb -query | grep "background-clr" | cut -f 2)
BACKGROUND_DIM=$(xrdb -query | grep "background-dim-clr" | cut -f 2)
FOREGROUND=$(xrdb -query | grep "foreground-clr" | cut -f 2)
FOREGROUND_DIM=$(xrdb -query | grep "foreground-dim-clr" | cut -f 2)

BLACK=$(xrdb -query | grep "black-clr" | cut -f 2)
RED=$(xrdb -query | grep "red-clr" | cut -f 2)
GREEN=$(xrdb -query | grep "green-clr" | cut -f 2)
YELLOW=$(xrdb -query | grep "yellow-clr" | cut -f 2)
BLUE=$(xrdb -query | grep "blue-clr" | cut -f 2)
MAGENTA=$(xrdb -query | grep "magenta-clr" | cut -f 2)
CYAN=$(xrdb -query | grep "cyan-clr" | cut -f 2)
WHITE=$(xrdb -query | grep "white-clr" | cut -f 2)



#set some bsp configs
bspc config window_gap $BSP_WINDOW_GAP
bspc config border_width 		  2
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       false

bspc config focused_border_color  "$BACKGROUND_DIM"
bspc config normal_border_color   "$BACKGROUND"
bspc config presel_feedback_color "$WHITE"

bspc config focus_follows_pointer  false

exec ~/.config/bspwm/autostart
