#! /bin/sh

####################################
######### ENV vars #################
####################################

export BSP_GAP=35
export POLYBAR_HEIGHT=20
export BSP_WINDOW_GAP=10

####################################
bspc monitor -d 1 2 3 4 5 

#add gaps around the screen
~/.config/sxhkd/scripts/bspwm-gap --gap

bspc config border_width          2

bspc config split_ratio           0.50
bspc config borderless_monocle    false
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config focused_border_color  "#45475A" 
bspc config normal_border_color   "#1F2430"
#bspc config focused_border_color  "#999999"
bspc config presel_feedback_color "#EEEEEE"

bspc rule -a 'firefox:*:Picture-in-Picture' state=floating sticky=on
#bspc rule -a feh state=floating 
#bspc rule -a firefox desktop='^2' 
#bspc rule -a ffplay state=floating 

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off



# launch autostart programs
exec $HOME/.config/bspwm/autostart
