require "core.plugins_config.nvim-tree"
require "core.plugins_config.lualine"
require "core.plugins_config.treesitter"
require "core.plugins_config.completions"
require "core.plugins_config.lsp_config"
require "core.plugins_config.barbar"
